version: 2

sources:
  - name: france-travail
    description: "Tables raw issues de l'extraction France Travail."
    database: "{{ 'data-market-386959' if target.type == 'bigquery' else 'staging_offres_ft' }}"
    schema: "{{ 'staging_dev' if target.type == 'bigquery' else 'main' }}"
    tables:
      - name: staging_offres_ft
        
  - name: geo-api
    description: "Tables raw issues de l'API geo (communes, departements, regions, epcis)."
    database: "{{ 'data-market-386959' if target.type == 'bigquery' else 'staging_offres_ft' }}"
    schema: "{{ 'staging_dev' if target.type == 'bigquery' else 'main' }}"
    tables:
      - name: staging_communes
      - name: staging_departements
      - name: staging_regions
      - name: staging_epcis
